-- Crear Tipo 
CREATE OR REPLACE TYPE DIMENSIONES_T AS OBJECT  (
  LARGO     NUMBER(3),
  ANCHO     NUMBER(3),
  ESPESOR 	NUMBER(3)
);
/

-- Crear la tabla tomando como estructura un TYPE 
CREATE TABLE PRODUCTOS (
  ART	 		VARCHAR2(3) PRIMARY KEY,
  DESCRIPCION	VARCHAR2(30),
  CATEGORIA		VARCHAR2(4),
  DIMENSIONES	DIMENSIONES_T,
  PRECIO		NUMBER(10,2)  
);

 
-- Insertar datos utilizando el orden de los campos por defecto en la creación
INSERT INTO PRODUCTOS VALUES 
 ('A01','PAL MOD.1D', 'C2', DIMENSIONES_T(3,4,3), 15.05);

INSERT INTO PRODUCTOS VALUES 
 ('A02','PIP MOD.1B', 'C1', DIMENSIONES_T(2,5,5), 30.25);

INSERT INTO PRODUCTOS VALUES 
 ('A03','PER MOD.1C', 'C2', DIMENSIONES_T(1,3,2), 25.95);

COMMIT;

-- Mostrar datos
SELECT ART, DESCRIPCION, CATEGORIA, P.DIMENSIONES.LARGO, P.DIMENSIONES.ANCHO , P.DIMENSIONES.ESPESOR, PRECIO FROM PRODUCTOS P;





